### PR TITLE
Use channel-post Post Apk Files

### PR DESCRIPTION
**Pull request by xireiki**
- Use channel-post to push multiple files together rather than separately

It's like this:
IMG_20240309_194333

### CODE REVIEW

**Comment by mgz0227** [comment]
已添加

**Comment by xireiki** [comment]
https://github.com/xireiki/legado/actions/runs/8214208312

**Comment by xireiki** [comment]
@mgz0227 你把 BOT_TOKEN 和 CHANNEL_ID 搞反了

**Comment by mgz0227** [comment]
修改了

**Pull request closed without merging**
